[package]
name = "zeton"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./x11-sys",
]

[dependencies]
libc = "0.2"
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.40"
toml = "0.7.3"
x11 = { path = "./x11-sys" }
